;; -*- mode: lisp -*-

;;Starts on fullscreen mode
(run-with-idle-timer 0.1 nil 'toggle-frame-fullscreen)

(add-to-list 'load-path (expand-file-name "~/.emacs.d/conf" user-emacs-directory))

(require 'init-constants)
(require 'init-ui)
(require 'init-path)
(require 'init-general)
(require 'init-packages)
(require 'init-async)
(require 'init-yasnippet)
(require 'init-helm)
(require 'init-magit)
(require 'init-projectile)
(require 'init-rbenv)
(require 'init-rvm)
(require 'init-web-mode)
(require 'init-php-mode)
(require 'init-yaml)
(require 'init-ruby)
(require 'init-inf-ruby)
(require 'init-robe)
(require 'init-helm-robe)
(require 'init-ruby-tools)
(require 'init-rspec-mode)
(require 'init-auto-complete)
(require 'init-ac-inf-ruby)
(require 'init-company)
;;(require 'init-company-inf-ruby)
(require 'init-ac-php)
(require 'init-neotree)
(require 'init-highlight-indentation)
;;(require 'init-indent-guide)
(require 'init-fill-column-indicator)
(require 'init-dash)
(require 'init-elixir-yasnippets)
(require 'init-smartparens)
(require 'init-undo-tree)
(require 'init-guide-key)

(defun custom/vcr-toggle ()
 (interactive)
 (if (getenv "VCR_OFF")
 (progn
 (setenv "VCR_OFF" nil)
 (message "VCR is ON"))
 (setenv "VCR_OFF" "true")
 (message "VCR is OFF")))
(global-set-key (kbd "M-0") 'custom/vcr-toggle)

(defun custom/remote-factory-toggle ()
 (interactive)
 (if (getenv "ENABLE_REMOTE_FACTORY_GIRL")
 (progn
 (setenv "ENABLE_REMOTE_FACTORY_GIRL" nil)
 (message "ENABLE_REMOTE_FACTORY_GIRL is ON"))
 (setenv "ENABLE_REMOTE_FACTORY_GIRL" "true")
 (message "ENABLE_REMOTE_FACTORY_GIRL is OFF")))
(global-set-key (kbd "M-9") 'custom/remote-factory-toggle)
